@AutoPilot.Api_HostAddress = http://localhost:8080
@BearerToken = replace_with_token_after_login

GET {{AutoPilot.Api_HostAddress}}/
Accept: application/json

###

GET {{AutoPilot.Api_HostAddress}}/api/health
Accept: application/json

###

POST {{AutoPilot.Api_HostAddress}}/api/auth/register
Content-Type: application/json

{
  "fullName": "Ravidu Avisara",
  "email": "ravidu@example.com",
  "password": "replaceWithStrongPassword1"
}

###

POST {{AutoPilot.Api_HostAddress}}/api/auth/login
Content-Type: application/json

{
  "email": "ravidu@example.com",
  "password": "replaceWithStrongPassword1"
}

###

GET {{AutoPilot.Api_HostAddress}}/api/users/me
Accept: application/json
Authorization: Bearer {{BearerToken}}

###

GET {{AutoPilot.Api_HostAddress}}/api/users
Accept: application/json
Authorization: Bearer {{BearerToken}}

###